### ISSUE TITLE
compiling error , help please

### ISSUE THREAD

**Issue by TxSnipper** [mareksuscak/asus-pce-n53-linux#5]
followed your tutorial and just installed a fresh copy of linux mint 19 cinnamon, v 3.8.6,  linux kernel 4.15.0-24,  I get this error stopping the first "Make", not a programmer, how do I fix this ?

  from /home/linuxos/asus-pce-n53-linux/os/linux/../../os/linux/sta_ioctl.c:30:
In function ‘memcpy’,
    inlined from ‘rt_ioctl_iwaplist’ at /home/linuxos/asus-pce-n53-linux/os/linux/../../os/linux/sta_ioctl.c:697:2:
./include/linux/string.h:340:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
scripts/Makefile.build:332: recipe for target '/home/linuxos/asus-pce-n53-linux/os/linux/../../os/linux/sta_ioctl.o' failed
make[2]: *** [/home/linuxos/asus-pce-n53-linux/os/linux/../../os/linux/sta_ioctl.o] Error 1
Makefile:1552: recipe for target '_module_/home/linuxos/asus-pce-n53-linux/os/linux' failed
make[1]: *** [_module_/home/linuxos/asus-pce-n53-linux/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-24-generic'
Makefile:384: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2

**Comment by Guite** [comment]
This has probably been fixed by #6. I had been using the driver with 4.15 kernels successfully. So I think this issue can be closed @mareksuscak

**Comment by mareksuscak** [comment]
Awesome, thank you for the heads up @Guite. Also I've just added you to the list of contributors.
